### ISSUE TITLE
Issue when attempting to loot crashed plane, results in crash

### ISSUE THREAD

**Issue by collatzcoder** [1whohears/DiamondStarCombat#50]
I'm back, and this issue is on a Minecraft server. This popped up, lagged out the whole server, and crashed it.
![image](https://github.com/user-attachments/assets/5feb70f2-e62a-4ffa-97e8-48ef18b9064c)
I can't seem to figure out what exactly is wrong but dscombat showed up there plenty so I will refer this to you.

**Comment by collatzcoder** [comment]
On further analysis it seems to be some sort of packet size overflow stemming from the drops of a dscombat plane.

**Comment by 1whohears** [comment]
I wrote this response yesterday but then never pressed send (face palm). this is dscombat's fault. I am not sure what could have caused that to happen but I'll add an if statement that prevents this from ever happening again. it's not a packet overflow. it's an error thrown by an RNG function cause it doesn't like that `origin > bound`. so I added a check where `if (origin > bound) { origin = bound - 1; }`  thanks for the report!

**Comment by 1whohears** [comment]
let me know if it happens again when I release v0.11.2

**Comment by collatzcoder** [comment]
Alright will do

**Comment by collatzcoder** [comment]
This one seems to be ok. It hasn't happened again
